import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { api } from '../lib/api';
import { GENRES_ZH, GENRES_EN } from '../lib/i18n';
import { useSeo } from '../lib/seo';

export default function Submit() {
  const { t, i18n } = useTranslation();
  const navigate = useNavigate();
  const lang = i18n.language;
  useSeo({
    title: lang === 'zh' ? '投稿新小说 | AI Novel' : 'Submit New Novel | AI Novel',
    description: lang === 'zh' ? '提交你的小说创意，AI 自动生成世界观与章节。' : 'Submit your novel idea and let AI generate worldbuilding and chapters.',
    lang,
    path: '/submit',
    noindex: true,
    enableHreflang: false,
  });
  const genres = lang === 'zh' ? GENRES_ZH : GENRES_EN;

  const [title, setTitle] = useState('');
  const [genre, setGenre] = useState(genres[0]);
  const [theme, setTheme] = useState('');
  const [guide, setGuide] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [modal, setModal] = useState<{ show: boolean; type: 'success' | 'error'; text: string }>({ show: false, type: 'success', text: '' });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!api.getToken()) { navigate('/login'); return; }
    setSubmitting(true);
    try {
      const r = await api.submit({
        title,
        genre,
        worldview: theme,
        outline: theme,
        core_conflict: theme,
        tone: guide || (lang === 'zh' ? '未指定' : 'Unspecified'),
        language: lang,
        characters: [{
          name: lang === 'zh' ? '待定' : 'TBD',
          role: 'protagonist',
          appearance: lang === 'zh' ? '由AI根据主题生成' : 'Generated by AI based on theme',
          personality: lang === 'zh' ? '由AI根据主题生成' : 'Generated by AI based on theme',
          motivation: lang === 'zh' ? '由AI根据主题生成' : 'Generated by AI based on theme',
          backstory: lang === 'zh' ? '由AI根据主题生成' : 'Generated by AI based on theme',
        }],
      });
      setModal({
        show: true,
        type: 'success',
        text: `${t('submit.successPrefix')}\n\n${t('submit.aiSuggestion')} ${r.ai_suggestion}\n${t('submit.riskLevel')} ${r.ai_risk}\n\n${t('submit.waitApproval')}`,
      });
      setTitle(''); setTheme(''); setGuide('');
    } catch (e: any) {
      setModal({ show: true, type: 'error', text: e.message });
    } finally { setSubmitting(false); }
  };

  return (
    <>
      <div className="page-intro">
        <h1 className="page-title">{t('submit.title')}</h1>
        <p className="page-subtitle">{t('submit.desc')}</p>
      </div>

      {/* 弹窗 */}
      {modal.show && (
        <div className="modal-overlay" onClick={() => setModal(p => ({ ...p, show: false }))}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-icon">{modal.type === 'success' ? '✅' : '❌'}</div>
            <p className={`modal-text ${modal.type === 'error' ? 'error' : ''}`}>{modal.text}</p>
            <button className="btn btn-block form-actions" onClick={() => setModal(p => ({ ...p, show: false }))}>{t('submit.confirm')}</button>
          </div>
        </div>
      )}

      <form onSubmit={handleSubmit} className="form-shell fade-up">
        <label>{t('submit.bookName')}</label>
        <input value={title} onChange={e => setTitle(e.target.value)} required placeholder={t('submit.placeholderTitle')} />

        <label>{t('submit.genre')}</label>
        <div className="genre-row">
          {genres.map(g => (
            <span key={g} className={`genre-tag ${genre === g ? 'active' : ''}`} onClick={() => setGenre(g)}>{g}</span>
          ))}
        </div>

        <label>{t('submit.theme')}</label>
        <textarea value={theme} onChange={e => setTheme(e.target.value)} required rows={5}
          placeholder={t('submit.placeholderTheme')} />

        <label>{t('submit.guide')}</label>
        <textarea value={guide} onChange={e => setGuide(e.target.value)} rows={4}
          placeholder={t('submit.placeholderGuide')} />

        <button type="submit" disabled={submitting} className="btn btn-block form-actions">
          {submitting ? t('submit.reviewing') : t('submit.submit')}
        </button>
      </form>
    </>
  );
}
