name = "ainovel-auth"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ainovel-db"
database_id = "2bb0a27e-24e3-49c0-be94-349b6a7b0266"

[[kv_namespaces]]
binding = "KV"
id = "a9f3eac236c448c48d1b6ef6d114e53a"
